### ISSUE TITLE
No multiple key keybindings possible.

### ISSUE THREAD

**Issue by Profpatsch** [cofi/evil-leader#18]
From Vim I am used to typing arbitrary long stuff after pressing leader.

E.g. `<leader>ba` to close the current buffer
or `<leader>b "` to switch to another buffer.

```
Debugger entered--Lisp error: (error "Key sequence b SPC starts with non-prefix key b")Debugger entered--Lisp error: (error "Key sequence b SPC starts with non-prefix key b")
```

**Comment by Profpatsch** [comment]
Now I’m highly confused:

```
(evil-leader/set-key
  "ci" 'evilnc-comment-or-uncomment-lines
  "cl" 'evilnc-comment-or-uncomment-to-the-line
  "cc" 'evilnc-copy-and-comment-lines
  "cp" 'evilnc-comment-or-uncomment-paragraphs
  "cr" 'comment-or-uncomment-region)
```

works. oO

**Comment by cofi** [comment]
Reoccuring Problem, see #6 .

Can it be that you used something like this?

```
"b" 'some-command
"ba" 'kill-this-buffer
```

**Comment by goldfeld** [comment]
With regards to the poster's comment that `c<key>` works, couldn't it have to do with `c` being naturally a vim prefix key outside leader? Just wondering, because I'm trying to bind `<leader>d` and it doesn't work, my set-leader doesn't have any other `<leader>d<key>` binds, yet when I press `<leader>d`, instead of executing the action, it expects a third key as if it were a prefix key. If I change it my action to be bound to e.g. `<leader>a`, it works. So I thought maybe it was some bug around the fact that d is a prefix key outside leader.

**Comment by cofi** [comment]
I don't think you are on the right track there.
`d` isn't  a prefix key as far as emacs is concerned (quick check: `C-h k d` describes the key and does not expect other keys).
Anyway, `<leader>` is a prefix key on its own meaning that it introduces its own subkeymap so evil's `d` will never be looked up.
If `<leader>d` awaits another key you (as in "your config") most probably introduced `<leader>d` as a prefix on its own, do `<leader>d C-h` to see the "sub" keys.

I'm closing it now, but don't hesitate do reopen if the problems persist and the mentioned checks don't reveal an configuration error.

**Comment by goldfeld** [comment]
Thanks for the tip, I see now that a plugin was sneakily mapping ,d (https://github.com/redguardtoo/evil-matchit)
