### ISSUE TITLE
Doesn't work in all modes

### ISSUE THREAD

**Issue by fullofcaffeine** [cofi/evil-leader#2]
Hi!

This plugin is awesome and brings my emacs workflow even nearer my vim one. However, I notice that in some buffers, the bindings don't work, i.e _Ibuffer_ _backtrace_. Would it be possible to force the evil-leader bindings globally, somehow?

Thanks,

Marcelo.

**Comment by cofi** [comment]
Hi,
great that it helps you :)

I don't know what `ibuffer backtrace` is, but if you mean `M-x ibuffer`, then it's because it turns up in evil's `emacs-state`.
By default evil-leader does only bind in `normal-state`, customize `evil-leader/in-all-states` to t and maybe `evil-leader/non-normal-prefix` (by default it's `C-`).

**Comment by fullofcaffeine** [comment]
Hi cofi,

Yeah, ibuffer and the backtrace buffers. I've bound ,b to ido-switch-buffer, and it doesn't work in those buffers, so I have to fallback to C-x b. I've tried setting evil-leader/in-all-states to t but it didn't seem to make any difference. How can I setup the evil-leader/non-normal-prefix var? How does that work?

Thanks!

Marcelo.

**Comment by cofi** [comment]
No it doesn't bind the leader key directly, so `,b` has no effect (or at least not the expected). It does bind it with the mentioned prefix, i.e. in this case `C-, b` invokes `ido-switch-buffer`.
In theory you could customize the prefix to `""` but I'd advise against it as you can't type a `,` in a normal way anymore.

I really should get around to write a README.

**Comment by fullofcaffeine** [comment]
Cool, got it. Thank you!
